# -*- coding: utf-8 -*-
"""Chatbot For How- To's , Troubleshooting  & Content Creation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9tOAi4oX_bEuu3WR_UZiU-PpLWzEm_H
"""

!pip install streamlit
!pip install os
!pip install requests
!pip install langchain.text_splitter

import streamlit as st
import os
import requests
import langchain.text_splitter #Fixed the typo in the module name
from langchain.text_splitter import RecursiveCharacterTextSplitter

os.environ["GEMINI_API_KEY"] = "AIzaSyAAje9hxCF6TxXb7_y-cZ2P7TQunb2Nc-8"

def generate_response(prompt):
    api_key = os.getenv("GEMINI_API_KEY")
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    url = "https://api.generativeai.google.com/v1beta/models/gemini-pro:generateMessage"
    data = {
        "message": prompt,
        "max_tokens": 150
    }
    response = requests.post(url, headers=headers, json=data)

    if response.status_code == 200:
        return response.json().get('candidates')[0].get('content', 'No response from model.')
    else:
        return f"Error: {response.status_code} - {response.text}"

st.title("Gemini AI Chatbot")
st.write("Chatbot for How-To's, Troubleshooting, and Content Creation using the Gemini API.")

user_input = st.text_input("Enter your prompt:")
if user_input:
  response = generate_response(user_input)
  st.write(response)

!streamlit run /usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py
